
POST http://localhost:5000/projects/createproject
Content-Type: application/json

{
    "project_name":"react-2",
    "project_desc":"design a react app",
    "project_timeline":"12/08/2022"
    
}
###
GET http://localhost:5000/projects/getallprojects


###
DELETE  http://localhost:5000/projects/deleteproject/1

{

}

###assign project
POST http://localhost:5000/projects/assignproject
Content-Type: application/json

{
    "id":"1",
    "user_id":"11"
  
}
###

POST http://localhost:5000/projects/completeproject
Content-Type: application/json

{
    "id":"1",
    "user_id":"11"
  
}


### registeruser
POST http://localhost:5000/users/registeruser
Content-Type: application/json

{
    "username":"Daniel",
    "email":"kakinyidk@gmail.com",
    "password":"12345678"  
}


###loginUser
POST http://localhost:5000/users/login
Content-Type: application/json

{
    
    "email":"lxwaihenya@gmail.com",
    "password":"12345678"  
}
###
GET http://localhost:5000/users/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJBbGV4IiwiZW1haWwiOiJseHdhaWhlbnlhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MDQ2OTkwMCwiZXhwIjoxNjYwNDcxOTAwfQ.J3a3_ZqkFh6MTRMMBfwDfbkeK5NYP1Yeug8HG8Eu2o4

###
GET http://localhost:5000/users/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJBbGV4IiwiZW1haWwiOiJseHdhaWhlbnlhQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY2MDQ2OTkwMCwiZXhwIjoxNjYwNDcxOTAwfQ.J3a3_ZqkFh6MTRMMBfwDfbkeK5NYP1Yeug8HG8Eu2o4
